AWSTemplateFormatVersion: "2010-09-09"
Description: "Small Test App Example Template"
Parameters:
  vpcID:
    Description: "VPC ID"
    Type: "AWS::EC2::Subnet::Id"
  subnetID:
    Description: "VPC Subnet IDs"
    Type: "AWS::EC2::Subnet::Id"
  appVersion:
    Description: "Application version"
    Type: "String"
  updateQueueUrl:
    Description: "SQS Queue URL"
    Type: "String"
Resources:
  jobQueue:
    Type: "AWS::SQS::Queue"
  WebServerInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-6e7bd919"
      SecurityGroupIds: "|Ref|securityGroupID"
      SubnetId: "|ref|subnetID"
      InstanceType: "t2.micro"
      "@TaupageUserData@":
        application_id: "|REF|AWS::StackName"
        application_version: "|Ref|appVersion"
        environment:
          JOB_QUEUE: "|GetAttr|jobQueue|Url"
          UPDATE_QUEUE: "|ref|updateQueueUrl"
