  AWSTemplateFormatVersion: "2010-09-09"
  Description: "AWS CloudFormation Template for a VPC in eu-west-1 with one subnet"
  Mappings:
    SubnetConfig:
      VPC-Values:
        CIDR: "10.10.0.0/16"
      Subnet-Values:
        CIDR: "10.10.0.0/18"
        AZ: "eu-west-1a"
  Resources:
    VPC:
      Type: "AWS::EC2::VPC"
      Properties:
        EnableDnsSupport: "true"
        EnableDnsHostnames: "true"
        CidrBlock: "10.10.0.0/18"
    Subnet:
      Type: "AWS::EC2::Subnet"
      Properties:
        AvailabilityZone: "eu-west-1a"
        VpcId: "|Ref|VPC"
        CidrBlock: "10.10.0.0/18"
  Outputs:
    id:
      Description: "ID of the newly created VPC"
      Value: "|Ref|VPC"
    subnet:
      Description: "SubnetId of the subnet"
      Value: "|Ref|Subnet"
