language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - git fetch --unshallow
env:
  - AWS_DEFAULT_REGION=eu-west-1
install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies

script: "pyb -X run_unit_tests"
after_success:
  - coveralls --verbose
