stacks:
    vpc:
        template: vpc.json
        region: eu-west-1
    baufi-sync-persistent-live:
        template: myapp-persistent.json
        parameters:
            vpc_id: Ref::vpc.id
            subnets:
                Ref::vpc.eu-west-1a,
                Ref::vpc.eu-west-1b,
                Ref::vpc.eu-west-1c,
    baufi-sync-volatile-live:
        template: myapp-volatile.json
        parameters:
            vpc_id: Ref::vpc.id
            subnets: Ref::subnets
            default_sg: Ref::security.default_sg