AWSTemplateFormatVersion: "2010-09-09"
Description: "Test Security Group"
Parameters:
  exposeTopicArn:
    Description: "Our expose topic arn"
    Type: "String"
  subnetID:
    Description: "Target VPC id"
    Type: "AWS::EC2::Subnet::Id"
  securityGroupID:
    Description: "Target VPC id"
    Type: "AWS::EC2::VPC::Id"
  appVersion:
    Description: "Target VPC id"
    Type: "String"
Resources:
  exposeQueue:
    Type: "AWS::SQS::Queue"
  WebServerInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-6e7bd919"
      SecurityGroupIds:
        -
          Ref: "securityGroupID"
      SubnetId:
        Ref: "subnetID"
      InstanceType: "t2.micro"
      KeyName:
        Ref: "sshKeyName"
      @TaupageUserData@:
        application_id: "|REF|AWS::StackName"
        application_version: "|Ref|appVersion"
        environment:
          QUEUE: "|GetAttr|exposeQueue|Url"
PostCustomResources:
  exposeTopicSubscription:
    Type: "SNS::Subscription"
    Properties:
      TopicArn:
        Ref: exposeTopicArn
      QueueName: "exposeQueue"


