region: eu-west-1
stacks:
  test-vpc:
    template: /Users/mhoyer/workspace/myapp/vpc.yml
  test-stack:
    template: /Users/mhoyer/workspace/myapp/app.yml
    parameters:
      vpcID: "ref::test-vpc.id"